//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapperator.ConsoleApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mapperator.ConsoleApp.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapperator is a tool for automatically improving osu! beatmaps.
        ///Basic usage:
        ///-e &quot;collection name&quot; &quot;output location&quot;
        ///-c &quot;data file&quot; &quot;beatmap file&quot; &quot;output location&quot;.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ML model....
        /// </summary>
        internal static string ConvertML_DoMapConvert_Loading_ML_model___ {
            get {
                return ResourceManager.GetString("ConvertML_DoMapConvert_Loading_ML_model___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find collection &apos;{0}&apos;..
        /// </summary>
        internal static string CouldNotFindCollection {
            get {
                return ResourceManager.GetString("CouldNotFindCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find file &apos;{0}&apos;..
        /// </summary>
        internal static string CouldNotFindFile {
            get {
                return ResourceManager.GetString("CouldNotFindFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of beatmap sets: {0}.
        /// </summary>
        internal static string Count_DoDataCount_Total_beatmap_sets___0_ {
            get {
                return ResourceManager.GetString("Count_DoDataCount_Total_beatmap_sets___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of beatmaps: {0}.
        /// </summary>
        internal static string Count_DoDataCount_Total_beatmaps___0_ {
            get {
                return ResourceManager.GetString("Count_DoDataCount_Total_beatmaps___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total duration: {0}.
        /// </summary>
        internal static string Count_DoDataCount_Total_duration___0_ {
            get {
                return ResourceManager.GetString("Count_DoDataCount_Total_duration___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total file size: {0} MB.
        /// </summary>
        internal static string Count_DoDataCount_Total_file_size___0__MB {
            get {
                return ResourceManager.GetString("Count_DoDataCount_Total_file_size___0__MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied beatmap set {0}/{1}.
        /// </summary>
        internal static string Dataset_DoDataExtraction_Copy_Update {
            get {
                return ResourceManager.GetString("Dataset_DoDataExtraction_Copy_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sets found.
        /// </summary>
        internal static string Dataset_DoDataExtraction_Count_Update {
            get {
                return ResourceManager.GetString("Dataset_DoDataExtraction_Count_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding beatmap sets....
        /// </summary>
        internal static string Dataset_DoDataExtraction_Finding_beatmap_sets___ {
            get {
                return ResourceManager.GetString("Dataset_DoDataExtraction_Finding_beatmap_sets___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing dataset....
        /// </summary>
        internal static string Dataset_DoDataExtraction_Writing_dataset___ {
            get {
                return ResourceManager.GetString("Dataset_DoDataExtraction_Writing_dataset___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OMDB tags file not found.
        /// </summary>
        internal static string Dataset_DoDataExtraction2_OMDB_tags_file_not_found {
            get {
                return ResourceManager.GetString("Dataset_DoDataExtraction2_OMDB_tags_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt audio file: {0}
        ///{1}.
        /// </summary>
        internal static string Dataset2_DoDataExtraction2_ {
            get {
                return ResourceManager.GetString("Dataset2_DoDataExtraction2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio file {0} not found in {1}.
        /// </summary>
        internal static string Dataset2_DoDataExtraction2_Audio_file__0__not_found_in__1_ {
            get {
                return ResourceManager.GetString("Dataset2_DoDataExtraction2_Audio_file__0__not_found_in__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beatmap sets skipped due to issues:.
        /// </summary>
        internal static string Dataset2_DoDataExtraction2_Beatmap_sets_skipped_due_to_issues_ {
            get {
                return ResourceManager.GetString("Dataset2_DoDataExtraction2_Beatmap_sets_skipped_due_to_issues_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beatmap sets with issues:.
        /// </summary>
        internal static string Dataset2_DoDataExtraction2_Beatmap_sets_with_issues_ {
            get {
                return ResourceManager.GetString("Dataset2_DoDataExtraction2_Beatmap_sets_with_issues_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beatmap sets with mismatched checksums:.
        /// </summary>
        internal static string Dataset2_DoDataExtraction2_Beatmap_sets_with_mismatched_checksums_ {
            get {
                return ResourceManager.GetString("Dataset2_DoDataExtraction2_Beatmap_sets_with_mismatched_checksums_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeatmapSetID not found in {0}. Skipping {1}..
        /// </summary>
        internal static string Dataset2_DoDataExtraction2_BeatmapSetID_not_found_in__0___Skipping__1__ {
            get {
                return ResourceManager.GetString("Dataset2_DoDataExtraction2_BeatmapSetID_not_found_in__0___Skipping__1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for missing data....
        /// </summary>
        internal static string Dataset2_DoDataExtraction2_Checking_for_missing_data___ {
            get {
                return ResourceManager.GetString("Dataset2_DoDataExtraction2_Checking_for_missing_data___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for missing metadata....
        /// </summary>
        internal static string Dataset2_DoDataExtraction2_Checking_for_missing_metadata___ {
            get {
                return ResourceManager.GetString("Dataset2_DoDataExtraction2_Checking_for_missing_metadata___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counting total file size and duration in the dataset....
        /// </summary>
        internal static string Dataset2_DoDataExtraction2_Counting_total_file_size_and_duration_in_the_dataset___ {
            get {
                return ResourceManager.GetString("Dataset2_DoDataExtraction2_Counting_total_file_size_and_duration_in_the_dataset__" +
                        "_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid .osz file name format: {0}. Expected format: &lt;SetID&gt; &lt;Artist&gt; - &lt;Title&gt;.osz.
        /// </summary>
        internal static string Dataset2_DoDataExtraction2_Invalid__osz_file_name_format___0___Expected_format___SetID___Artist_____Title__osz {
            get {
                return ResourceManager.GetString("Dataset2_DoDataExtraction2_Invalid__osz_file_name_format___0___Expected_format___" +
                        "SetID___Artist_____Title__osz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading existing metadata....
        /// </summary>
        internal static string Dataset2_DoDataExtraction2_Loading_existing_metadata___ {
            get {
                return ResourceManager.GetString("Dataset2_DoDataExtraction2_Loading_existing_metadata___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading existing sets skipped....
        /// </summary>
        internal static string Dataset2_DoDataExtraction2_Loading_existing_sets_skipped___ {
            get {
                return ResourceManager.GetString("Dataset2_DoDataExtraction2_Loading_existing_sets_skipped___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading existing sets with issues....
        /// </summary>
        internal static string Dataset2_DoDataExtraction2_Loading_existing_sets_with_issues___ {
            get {
                return ResourceManager.GetString("Dataset2_DoDataExtraction2_Loading_existing_sets_with_issues___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading existing sets with mismatched checksums....
        /// </summary>
        internal static string Dataset2_DoDataExtraction2_Loading_existing_sets_with_mismatched_checksums___ {
            get {
                return ResourceManager.GetString("Dataset2_DoDataExtraction2_Loading_existing_sets_with_mismatched_checksums___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading online cache....
        /// </summary>
        internal static string Dataset2_DoDataExtraction2_Loading_online_cache___ {
            get {
                return ResourceManager.GetString("Dataset2_DoDataExtraction2_Loading_online_cache___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing audio file for {0}.
        /// </summary>
        internal static string Dataset2_DoDataExtraction2_Missing_audio_file_for__0_ {
            get {
                return ResourceManager.GetString("Dataset2_DoDataExtraction2_Missing_audio_file_for__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing beatmap for {0}.
        /// </summary>
        internal static string Dataset2_DoDataExtraction2_Missing_beatmap_for__0_ {
            get {
                return ResourceManager.GetString("Dataset2_DoDataExtraction2_Missing_beatmap_for__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing metadata for {0}.
        /// </summary>
        internal static string Dataset2_DoDataExtraction2_Missing_metadata_for__0_ {
            get {
                return ResourceManager.GetString("Dataset2_DoDataExtraction2_Missing_metadata_for__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing ranked beatmap sets:.
        /// </summary>
        internal static string Dataset2_DoDataExtraction2_Missing_ranked_beatmap_sets_ {
            get {
                return ResourceManager.GetString("Dataset2_DoDataExtraction2_Missing_ranked_beatmap_sets_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No .osu file found in {0}. Skipping..
        /// </summary>
        internal static string Dataset2_DoDataExtraction2_No__osu_file_found_in__0___Skipping_ {
            get {
                return ResourceManager.GetString("Dataset2_DoDataExtraction2_No__osu_file_found_in__0___Skipping_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping {0} because checksum does not match..
        /// </summary>
        internal static string Dataset2_DoDataExtraction2_Skipping__0__because_checksum_does_not_match_ {
            get {
                return ResourceManager.GetString("Dataset2_DoDataExtraction2_Skipping__0__because_checksum_does_not_match_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping {0} because checksum does not match and BeatmapID is not found..
        /// </summary>
        internal static string Dataset2_DoDataExtraction2_Skipping__0__because_checksum_does_not_match_and_BeatmapID_is_not_found_ {
            get {
                return ResourceManager.GetString("Dataset2_DoDataExtraction2_Skipping__0__because_checksum_does_not_match_and_Beatm" +
                        "apID_is_not_found_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping {0} because it is not ranked..
        /// </summary>
        internal static string Dataset2_DoDataExtraction2_Skipping__0__because_it_is_not_ranked_ {
            get {
                return ResourceManager.GetString("Dataset2_DoDataExtraction2_Skipping__0__because_it_is_not_ranked_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping {0} because ìt is not ranked..
        /// </summary>
        internal static string Dataset2_DoDataExtraction2_Skipping__0__because_ìt_is_not_ranked_ {
            get {
                return ResourceManager.GetString("Dataset2_DoDataExtraction2_Skipping__0__because_ìt_is_not_ranked_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get osu! API access token. Make sure your ClientId and ClientSecret are correctly set in config.json..
        /// </summary>
        internal static string Dataset2_GetAccessToken_Failed_to_get_osu__API_access_token__Make_sure_your_ClientId_and_ClientSecret_are_correctly_set_in_config_json_ {
            get {
                return ResourceManager.GetString("Dataset2_GetAccessToken_Failed_to_get_osu__API_access_token__Make_sure_your_Clien" +
                        "tId_and_ClientSecret_are_correctly_set_in_config_json_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate limited, waiting 10 seconds....
        /// </summary>
        internal static string Dataset2_GetBeatmapsetInfo_Rate_limited__waiting_10_seconds___ {
            get {
                return ResourceManager.GetString("Dataset2_GetBeatmapsetInfo_Rate_limited__waiting_10_seconds___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed-out, waiting 10 seconds....
        /// </summary>
        internal static string Dataset2_GetBeatmapsetInfo_Timed_out__waiting_10_seconds___ {
            get {
                return ResourceManager.GetString("Dataset2_GetBeatmapsetInfo_Timed_out__waiting_10_seconds___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading file &apos;{0}&apos;:
        ///{1}.
        /// </summary>
        internal static string ErrorReadingFile {
            get {
                return ResourceManager.GetString("ErrorReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} ({2}) [{3}].
        /// </summary>
        internal static string FullBeatmapName {
            get {
                return ResourceManager.GetString("FullBeatmapName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough arguments provided. Expected {0} arguments..
        /// </summary>
        internal static string NotEnoughArguments {
            get {
                return ResourceManager.GetString("NotEnoughArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} matcher is not compatible with building..
        /// </summary>
        internal static string Program_DoBuildGraph_The__0__matcher_is_not_compatible_with_building_ {
            get {
                return ResourceManager.GetString("Program_DoBuildGraph_The__0__matcher_is_not_compatible_with_building_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding data....
        /// </summary>
        internal static string Program_DoMapConvert_Adding_data___ {
            get {
                return ResourceManager.GetString("Program_DoMapConvert_Adding_data___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructing beatmap....
        /// </summary>
        internal static string Program_DoMapConvert_Constructing_beatmap___ {
            get {
                return ResourceManager.GetString("Program_DoMapConvert_Constructing_beatmap___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting spacing to reference beatmap....
        /// </summary>
        internal static string Program_DoMapConvert_Converting_spacing_to_reference_beatmap___ {
            get {
                return ResourceManager.GetString("Program_DoMapConvert_Converting_spacing_to_reference_beatmap___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed Time is {0} ms.
        /// </summary>
        internal static string Program_DoMapConvert_Elapsed_Time_is {
            get {
                return ResourceManager.GetString("Program_DoMapConvert_Elapsed_Time_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting data....
        /// </summary>
        internal static string Program_DoMapConvert_Extracting_data___ {
            get {
                return ResourceManager.GetString("Program_DoMapConvert_Extracting_data___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t parse this map: .
        /// </summary>
        internal static string Program_PatternSearchMap_Can_t_parse_this_map__ {
            get {
                return ResourceManager.GetString("Program_PatternSearchMap_Can_t_parse_this_map__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found match {0} in beatmap: {1}.
        /// </summary>
        internal static string Program_PatternSearchMap_Found_match__0__in_beatmap___1_ {
            get {
                return ResourceManager.GetString("Program_PatternSearchMap_Found_match__0__in_beatmap___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello world!.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command: &quot;{0}&quot;.
        /// </summary>
        internal static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is only compatible with Windows..
        /// </summary>
        internal static string WindowsOnlyOperation {
            get {
                return ResourceManager.GetString("WindowsOnlyOperation", resourceCulture);
            }
        }
    }
}
