//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapperator.ConsoleApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mapperator.ConsoleApp.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapperator is a tool for automatically improving osu! beatmaps.
        ///Basic usage:
        ///-e &quot;collection name&quot; &quot;output location&quot;
        ///-c &quot;data file&quot; &quot;beatmap file&quot; &quot;output location&quot;.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find collection &apos;{0}&apos;..
        /// </summary>
        internal static string CouldNotFindCollection {
            get {
                return ResourceManager.GetString("CouldNotFindCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find file &apos;{0}&apos;..
        /// </summary>
        internal static string CouldNotFindFile {
            get {
                return ResourceManager.GetString("CouldNotFindFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading file &apos;{0}&apos;:
        ///{1}.
        /// </summary>
        internal static string ErrorReadingFile {
            get {
                return ResourceManager.GetString("ErrorReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough arguments provided. Expected {0} arguments..
        /// </summary>
        internal static string NotEnoughArguments {
            get {
                return ResourceManager.GetString("NotEnoughArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} matcher is not compatible with building..
        /// </summary>
        internal static string Program_DoBuildGraph_The__0__matcher_is_not_compatible_with_building_ {
            get {
                return ResourceManager.GetString("Program_DoBuildGraph_The__0__matcher_is_not_compatible_with_building_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding data....
        /// </summary>
        internal static string Program_DoMapConvert_Adding_data___ {
            get {
                return ResourceManager.GetString("Program_DoMapConvert_Adding_data___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructing beatmap....
        /// </summary>
        internal static string Program_DoMapConvert_Constructing_beatmap___ {
            get {
                return ResourceManager.GetString("Program_DoMapConvert_Constructing_beatmap___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed Time is {0} ms.
        /// </summary>
        internal static string Program_DoMapConvert_Elapsed_Time_is {
            get {
                return ResourceManager.GetString("Program_DoMapConvert_Elapsed_Time_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting data....
        /// </summary>
        internal static string Program_DoMapConvert_Extracting_data___ {
            get {
                return ResourceManager.GetString("Program_DoMapConvert_Extracting_data___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t parse this map: .
        /// </summary>
        internal static string Program_PatternSearchMap_Can_t_parse_this_map__ {
            get {
                return ResourceManager.GetString("Program_PatternSearchMap_Can_t_parse_this_map__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found match {0} in beatmap: {1}.
        /// </summary>
        internal static string Program_PatternSearchMap_Found_match__0__in_beatmap___1_ {
            get {
                return ResourceManager.GetString("Program_PatternSearchMap_Found_match__0__in_beatmap___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello world!.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command: &quot;{0}&quot;.
        /// </summary>
        internal static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is only compatible with Windows..
        /// </summary>
        internal static string WindowsOnlyOperation {
            get {
                return ResourceManager.GetString("WindowsOnlyOperation", resourceCulture);
            }
        }
    }
}
